CREATE TABLE dbo._databases (
    _InstanceID                                 int                 NOT NULL CONSTRAINT FK__databases__InstanceID   REFERENCES dbo.Instance     (InstanceID),
    _DatabaseID                                 int                     NULL CONSTRAINT FK__databases__DatabaseID   REFERENCES dbo.[Database]   (DatabaseID),
    _InsertDate                                 datetime2           NOT NULL CONSTRAINT DF__databases__InsertDate   DEFAULT (SYSUTCDATETIME()),
    _ModifyDate                                 datetime2           NOT NULL CONSTRAINT DF__databases__ModifyDate   DEFAULT (SYSUTCDATETIME()),
    _RowHash                                    binary(32)          NOT NULL,
    _ValidFrom                                  datetime2           GENERATED ALWAYS AS ROW START   NOT NULL,
    _ValidTo                                    datetime2           GENERATED ALWAYS AS ROW END     NOT NULL,
    --
    [name]                                      nvarchar(128)       NOT NULL,
    database_id                                 int                 NOT NULL,
    source_database_id                          int                     NULL,
    owner_sid                                   varbinary(85)           NULL,
    create_date                                 datetime            NOT NULL,
    [compatibility_level]                       tinyint             NOT NULL,
    collation_name                              nvarchar(128)           NULL,
    user_access                                 tinyint                 NULL,
    user_access_desc                            nvarchar(60)            NULL,
    is_read_only                                bit                     NULL,
    is_auto_close_on                            bit                 NOT NULL,
    is_auto_shrink_on                           bit                     NULL,
    [state]                                     tinyint                 NULL,
    state_desc                                  nvarchar(60)            NULL,
    is_in_standby                               bit                     NULL,
    is_cleanly_shutdown                         bit                     NULL,
    is_supplemental_logging_enabled             bit                     NULL,
    snapshot_isolation_state                    tinyint                 NULL,
    snapshot_isolation_state_desc               nvarchar(60)            NULL,
    is_read_committed_snapshot_on               bit                     NULL,
    recovery_model                              tinyint                 NULL,
    recovery_model_desc                         nvarchar(60)            NULL,
    page_verify_option                          tinyint                 NULL,
    page_verify_option_desc                     nvarchar(60)            NULL,
    is_auto_create_stats_on                     bit                     NULL,
    is_auto_create_stats_incremental_on         bit                     NULL,
    is_auto_update_stats_on                     bit                     NULL,
    is_auto_update_stats_async_on               bit                     NULL,
    is_ansi_null_default_on                     bit                     NULL,
    is_ansi_nulls_on                            bit                     NULL,
    is_ansi_padding_on                          bit                     NULL,
    is_ansi_warnings_on                         bit                     NULL,
    is_arithabort_on                            bit                     NULL,
    is_concat_null_yields_null_on               bit                     NULL,
    is_numeric_roundabort_on                    bit                     NULL,
    is_quoted_identifier_on                     bit                     NULL,
    is_recursive_triggers_on                    bit                     NULL,
    is_cursor_close_on_commit_on                bit                     NULL,
    is_local_cursor_default                     bit                     NULL,
    is_fulltext_enabled                         bit                     NULL,
    is_trustworthy_on                           bit                     NULL,
    is_db_chaining_on                           bit                     NULL,
    is_parameterization_forced                  bit                     NULL,
    is_master_key_encrypted_by_server           bit                 NOT NULL,
    is_query_store_on                           bit                     NULL,
    is_published                                bit                 NOT NULL,
    is_subscribed                               bit                 NOT NULL,
    is_merge_published                          bit                 NOT NULL,
    is_distributor                              bit                 NOT NULL,
    is_sync_with_backup                         bit                 NOT NULL,
    service_broker_guid                         uniqueidentifier    NOT NULL,
    is_broker_enabled                           bit                 NOT NULL,
    log_reuse_wait                              tinyint                 NULL,
    log_reuse_wait_desc                         nvarchar(60)            NULL,
    is_date_correlation_on                      bit                 NOT NULL,
    is_cdc_enabled                              bit                 NOT NULL,
    is_encrypted                                bit                     NULL,
    is_honor_broker_priority_on                 bit                     NULL,
    replica_id                                  uniqueidentifier        NULL,
    group_database_id                           uniqueidentifier        NULL,
    resource_pool_id                            int                     NULL,
    default_language_lcid                       smallint                NULL,
    default_language_name                       nvarchar(128)           NULL,
    default_fulltext_language_lcid              int                     NULL,
    default_fulltext_language_name              nvarchar(128)           NULL,
    is_nested_triggers_on                       bit                     NULL,
    is_transform_noise_words_on                 bit                     NULL,
    two_digit_year_cutoff                       smallint                NULL,
    containment                                 tinyint                 NULL,
    containment_desc                            nvarchar(60)            NULL,
    target_recovery_time_in_seconds             int                     NULL,
    [delayed_durability]                        int                     NULL,
    delayed_durability_desc                     nvarchar(60)            NULL,
    is_memory_optimized_elevate_to_snapshot_on  bit                     NULL,
    is_federation_member                        bit                     NULL,
    is_remote_data_archive_enabled              bit                     NULL,
    is_mixed_page_allocation_on                 bit                     NULL,
    is_temporal_history_retention_enabled       bit                     NULL,
    catalog_collation_type                      int                     NULL, -- Added: SQL Server 2019 - Deviation: NOT NULL
    catalog_collation_type_desc                 nvarchar(60)            NULL, -- Added: SQL Server 2019
    physical_database_name                      nvarchar(128)           NULL, -- Added: SQL Server 2019
    is_result_set_caching_on                    bit                     NULL, -- Added: SQL Server 2019
    is_accelerated_database_recovery_on         bit                     NULL, -- Added: SQL Server 2019
    is_tempdb_spill_to_remote_store             bit                     NULL, -- Added: SQL Server 2019
    is_stale_page_detection_on                  bit                     NULL, -- Added: SQL Server 2019
    is_memory_optimized_enabled                 bit                     NULL, -- Added: SQL Server 2019
    is_data_retention_enabled                   bit                     NULL, -- Added: SQL Server 2022
    is_ledger_on                                bit                     NULL, -- Added: SQL Server 2022
    is_change_feed_enabled                      bit                     NULL, -- Added: SQL Server 2022

    PERIOD FOR SYSTEM_TIME (_ValidFrom, _ValidTo),

    CONSTRAINT CPK__databases__InstanceID_name PRIMARY KEY CLUSTERED (_InstanceID, [name]),
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo._databases_history, DATA_CONSISTENCY_CHECK = ON, HISTORY_RETENTION_PERIOD = 6 MONTH));
GO
