CREATE TABLE dbo._DATABASEPROPERTYEX (
	_DatabaseID									int				NOT	NULL CONSTRAINT FK__DATABASEPROPERTYEX__DatabaseID REFERENCES dbo.[Database] (DatabaseID),
	_CollectionDate								datetime2		NOT	NULL,
	--
	Collation									nvarchar(128)		NULL,
	ComparisonStyle								int					NULL,
	Edition										nvarchar(64)		NULL,
	IsAnsiNullDefault							int					NULL,
	IsAnsiNullsEnabled							int					NULL,
	IsAnsiPaddingEnabled						int					NULL,
	IsAnsiWarningsEnabled						int					NULL,
	IsArithmeticAbortEnabled					int					NULL,
	IsAutoClose									int					NULL,
	IsAutoCreateStatistics						int					NULL,
	IsAutoCreateStatisticsIncremental			int					NULL,
	IsAutoShrink								int					NULL,
	IsAutoUpdateStatistics						int					NULL,
	IsClone										tinyint				NULL,
	IsCloseCursorsOnCommitEnabled				int					NULL,
	IsDatabaseSuspendedForSnapshotBackup		int					NULL,
	IsFulltextEnabled							int					NULL,
	IsInStandBy									int					NULL,
	IsLocalCursorsDefault						int					NULL,
	IsMemoryOptimizedElevateToSnapshotEnabled	int					NULL,
	IsMergePublished							int					NULL,
	IsNullConcat								int					NULL,
	IsNumericRoundAbortEnabled					int					NULL,
	IsParameterizationForced					int					NULL,
	IsQuotedIdentifiersEnabled					int					NULL,
	IsPublished									int					NULL,
	IsRecursiveTriggersEnabled					int					NULL,
	IsSubscribed								int					NULL,
	IsSyncWithBackup							int					NULL,
	IsTornPageDetectionEnabled					int					NULL,
	IsVerifiedClone								tinyint				NULL,
	IsXTPSupported								tinyint				NULL,
	LastGoodCheckDbTime							datetime			NULL,
	LCID										int					NULL,
	MaxSizeInBytes								bigint				NULL,
	[Recovery]									nvarchar(128)		NULL,
	ServiceObjective							nvarchar(32)		NULL,
	ServiceObjectiveId							uniqueidentifier	NULL,
	SQLSortOrder								tinyint				NULL,
	[Status]									nvarchar(128)		NULL,
	Updateability								nvarchar(128)		NULL,
	UserAccess									nvarchar(128)		NULL,
	[Version]									int					NULL,
	ReplicaID									nvarchar(128)		NULL,

	INDEX CIX__DATABASEPROPERTYEX__DatabaseID UNIQUE CLUSTERED (_DatabaseID),
);
GO
