CREATE TABLE dbo._dm_hadr_database_replica_states (
    _DatabaseID                 int                 NOT NULL CONSTRAINT FK__dm_hadr_database_replica_states__DatabaseID REFERENCES dbo.[Database] (DatabaseID),
    _CollectionDate             datetime2           NOT NULL,
    --
    database_id                 int                 NOT NULL,
    group_id                    uniqueidentifier    NOT NULL,
    replica_id                  uniqueidentifier    NOT NULL,
    group_database_id           uniqueidentifier    NOT NULL,
    is_local                    bit                     NULL,
    is_primary_replica          bit                     NULL,
    synchronization_state       tinyint                 NULL,
    synchronization_state_desc  nvarchar(60)            NULL,
    is_commit_participant       bit                     NULL,
    synchronization_health      tinyint                 NULL,
    synchronization_health_desc nvarchar(60)            NULL,
    database_state              tinyint                 NULL,
    database_state_desc         nvarchar(60)            NULL,
    is_suspended                bit                     NULL,
    suspend_reason              tinyint                 NULL,
    suspend_reason_desc         nvarchar(60)            NULL,
    recovery_lsn                numeric(25,0)           NULL,
    truncation_lsn              numeric(25,0)           NULL,
    last_sent_lsn               numeric(25,0)           NULL,
    last_sent_time              datetime                NULL,
    last_received_lsn           numeric(25,0)           NULL,
    last_received_time          datetime                NULL,
    last_hardened_lsn           numeric(25,0)           NULL,
    last_hardened_time          datetime                NULL,
    last_redone_lsn             numeric(25,0)           NULL,
    last_redone_time            datetime                NULL,
    log_send_queue_size         bigint                  NULL,
    log_send_rate               bigint                  NULL,
    redo_queue_size             bigint                  NULL,
    redo_rate                   bigint                  NULL,
    filestream_send_rate        bigint                  NULL,
    end_of_log_lsn              numeric(25,0)           NULL,
    last_commit_lsn             numeric(25,0)           NULL,
    last_commit_time            datetime                NULL,
    low_water_mark_for_ghosts   bigint                  NULL,
    secondary_lag_seconds       bigint                  NULL,
    quorum_commit_lsn           numeric(25,0)           NULL, -- Added: SQL Server 2019
    quorum_commit_time          datetime                NULL, -- Added: SQL Server 2019

    INDEX CIX__dm_hadr_database_replica_states__DatabaseID_replica_id UNIQUE CLUSTERED (_DatabaseID, replica_id),
);
GO
