CREATE TABLE dbo._OBJECTPROPERTYEX (
    _DatabaseID                          int           NOT NULL CONSTRAINT FK__OBJECTPROPERTYEX__DatabaseID REFERENCES dbo.[Database] (_DatabaseID),
    _ObjectID                            int           NOT NULL CONSTRAINT FK__OBJECTPROPERTYEX__ObjectID   REFERENCES dbo.[Object]   (_ObjectID),
    --
    _InsertDate                          datetime2     NOT NULL CONSTRAINT DF__OBJECTPROPERTYEX__InsertDate DEFAULT (SYSUTCDATETIME()),
    _ModifyDate                          datetime2     NOT NULL CONSTRAINT DF__OBJECTPROPERTYEX__ModifyDate DEFAULT (SYSUTCDATETIME()),
    _RowHash                             binary(32)    NOT NULL,
    --
    BaseType                             char(2)         NULL,
    CnstIsClustKey                       int             NULL,
    CnstIsColumn                         int             NULL,
    CnstIsDeleteCascade                  int             NULL,
    CnstIsDisabled                       int             NULL,
    CnstIsNonclustKey                    int             NULL,
    CnstIsNotRepl                        int             NULL,
    CnstIsNotTrusted                     int             NULL,
    CnstIsUpdateCascade                  int             NULL,
    ExecIsAfterTrigger                   int             NULL,
    ExecIsAnsiNullsOn                    int             NULL,
    ExecIsDeleteTrigger                  int             NULL,
    ExecIsFirstDeleteTrigger             int             NULL,
    ExecIsFirstInsertTrigger             int             NULL,
    ExecIsFirstUpdateTrigger             int             NULL,
    ExecIsInsertTrigger                  int             NULL,
    ExecIsInsteadOfTrigger               int             NULL,
    ExecIsLastDeleteTrigger              int             NULL,
    ExecIsLastInsertTrigger              int             NULL,
    ExecIsLastUpdateTrigger              int             NULL,
    ExecIsQuotedIdentOn                  int             NULL,
    ExecIsStartup                        int             NULL,
    ExecIsTriggerDisabled                int             NULL,
    ExecIsTriggerNotForRepl              int             NULL,
    ExecIsUpdateTrigger                  int             NULL,
    ExecIsWithNativeCompilation          int             NULL,
    HasAfterTrigger                      int             NULL,
    HasDeleteTrigger                     int             NULL,
    HasInsertTrigger                     int             NULL,
    HasInsteadOfTrigger                  int             NULL,
    HasUpdateTrigger                     int             NULL,
    IsAnsiNullsOn                        int             NULL,
    IsCheckCnst                          int             NULL,
    IsConstraint                         int             NULL,
    IsDefault                            int             NULL,
    IsDefaultCnst                        int             NULL,
    IsDeterministic                      int             NULL,
    IsEncrypted                          int             NULL,
    IsExecuted                           int             NULL,
    IsExtendedProc                       int             NULL,
    IsForeignKey                         int             NULL,
    IsIndexed                            int             NULL,
    IsIndexable                          int             NULL,
    IsInlineFunction                     int             NULL,
    IsMSShipped                          int             NULL,
    IsPrecise                            int             NULL,
    IsPrimaryKey                         int             NULL,
    IsProcedure                          int             NULL,
    IsQuotedIdentOn                      int             NULL,
    IsQueue                              int             NULL,
    IsReplProc                           int             NULL,
    IsRule                               int             NULL,
    IsScalarFunction                     int             NULL,
    IsSchemaBound                        int             NULL,
    IsSystemTable                        int             NULL,
    IsSystemVerified                     int             NULL,
    IsTable                              int             NULL,
    IsTableFunction                      int             NULL,
    IsTrigger                            int             NULL,
    IsUniqueCnst                         int             NULL,
    IsUserTable                          int             NULL,
    IsView                               int             NULL,
    OwnerId                              int             NULL,
    SchemaId                             int             NULL,
    SystemDataAccess                     int             NULL,
    TableDeleteTrigger                   int             NULL,
    TableDeleteTriggerCount              int             NULL,
    TableFullTextMergeStatus             int             NULL,
    TableFullTextBackgroundUpdateIndexOn int             NULL,
    TableFulltextCatalogId               int             NULL,
    TableFullTextChangeTrackingOn        int             NULL,
    TableFulltextKeyColumn               int             NULL,
    TableFulltextPopulateStatus          int             NULL,
    TableFullTextSemanticExtraction      int             NULL,
    TableHasActiveFulltextIndex          int             NULL,
    TableHasCheckCnst                    int             NULL,
    TableHasClustIndex                   int             NULL,
    TableHasDefaultCnst                  int             NULL,
    TableHasDeleteTrigger                int             NULL,
    TableHasForeignKey                   int             NULL,
    TableHasForeignRef                   int             NULL,
    TableHasIdentity                     int             NULL,
    TableHasIndex                        int             NULL,
    TableHasInsertTrigger                int             NULL,
    TableHasNonclustIndex                int             NULL,
    TableHasPrimaryKey                   int             NULL,
    TableHasRowGuidCol                   int             NULL,
    TableHasTextImage                    int             NULL,
    TableHasTimestamp                    int             NULL,
    TableHasUniqueCnst                   int             NULL,
    TableHasUpdateTrigger                int             NULL,
    TableHasVarDecimalStorageFormat      int             NULL,
    TableInsertTrigger                   int             NULL,
    TableInsertTriggerCount              int             NULL,
    TableIsFake                          int             NULL,
    TableIsLockedOnBulkLoad              int             NULL,
    TableIsMemoryOptimized               int             NULL,
    TableIsPinned                        int             NULL,
    TableTextInRowLimit                  int             NULL,
    TableUpdateTrigger                   int             NULL,
    TableUpdateTriggerCount              int             NULL,
    UserDataAccess                       int             NULL,
    TableHasColumnSet                    int             NULL,
    Cardinality                          bigint          NULL,
    TableTemporalType                    int             NULL,

    CONSTRAINT CPK__OBJECTPROPERTYEX__ObjectID PRIMARY KEY CLUSTERED (_ObjectID),
    INDEX IX__OBJECTPROPERTYEX__DatabaseID NONCLUSTERED (_DatabaseID),
    INDEX IX__OBJECTPROPERTYEX__ObjectID_Cardinality NONCLUSTERED (_ObjectID, Cardinality),
);
GO
