CREATE TABLE dbo._sysarticles_history (
    _DatabaseID                 int             NOT NULL,
    _ObjectID                   int             NOT NULL,
    _InsertDate                 datetime2       NOT NULL,
    _ModifyDate                 datetime2       NOT NULL,
    _RowHash                    binary(32)      NOT NULL,
    _ValidFrom                  datetime2       NOT NULL,
    _ValidTo                    datetime2       NOT NULL,
    --
    artid                       int             NOT NULL,
    creation_script             nvarchar(255)       NULL,
    del_cmd                     nvarchar(255)       NULL,
    [description]               nvarchar(255)       NULL,
    dest_table                  nvarchar(128)   NOT NULL,
    [filter]                    int             NOT NULL,
    filter_clause               nvarchar(MAX)       NULL,
    ins_cmd                     nvarchar(255)       NULL,
    [name]                      nvarchar(128)   NOT NULL,
    [objid]                     int             NOT NULL,
    pubid                       int             NOT NULL,
    pre_creation_cmd            tinyint         NOT NULL,
    [status]                    tinyint         NOT NULL,
    sync_objid                  int             NOT NULL,
    [type]                      tinyint         NOT NULL,
    upd_cmd                     nvarchar(255)       NULL,
    schema_option               binary(8)           NULL,
    dest_owner                  nvarchar(128)       NULL,
    ins_scripting_proc          int                 NULL,
    del_scripting_proc          int                 NULL,
    upd_scripting_proc          int                 NULL,
    custom_script               nvarchar(2048)      NULL,
    fire_triggers_on_snapshot   bit             NOT NULL,

    INDEX CIX__sysarticles_history__ValidTo__ValidFrom CLUSTERED (_ValidTo, _ValidFrom) WITH (DATA_COMPRESSION = PAGE),
);
GO
