CREATE TABLE dbo._syspublications (
	_DatabaseID						int					NOT	NULL CONSTRAINT FK__syspublications__DatabaseID REFERENCES dbo.[Database] (DatabaseID),
	_CollectionDate					datetime2			NOT	NULL,
	--
	[description]					nvarchar(255)		NULL,
	[name]							nvarchar(128)	NOT	NULL,
	pubid							int				NOT	NULL,
	repl_freq						tinyint			NOT	NULL,
	[status]						tinyint			NOT	NULL,
	sync_method						tinyint			NOT	NULL,
	snapshot_jobid					binary(16)			NULL,
	independent_agent				bit				NOT	NULL,
	immediate_sync					bit				NOT	NULL,
	enabled_for_internet			bit				NOT	NULL,
	allow_push						bit				NOT	NULL,
	allow_pull						bit				NOT	NULL,
	allow_anonymous					bit				NOT	NULL,
	immediate_sync_ready			bit				NOT	NULL,
	allow_sync_tran					bit				NOT	NULL,
	autogen_sync_procs				bit				NOT	NULL,
	[retention]						int					NULL,
	allow_queued_tran				bit				NOT	NULL,
	snapshot_in_defaultfolder		bit				NOT	NULL,
	alt_snapshot_folder				nvarchar(255)		NULL,
	pre_snapshot_script				nvarchar(255)		NULL,
	post_snapshot_script			nvarchar(255)		NULL,
	compress_snapshot				bit				NOT	NULL,
	ftp_address						nvarchar(128)		NULL,
	ftp_port						int				NOT	NULL,
	ftp_subdirectory				nvarchar(255)		NULL,
	ftp_login						nvarchar(128)		NULL,
	ftp_password					nvarchar(524)		NULL,
	allow_dts						bit				NOT	NULL,
	allow_subscription_copy			bit				NOT	NULL,
	centralized_conflicts			bit					NULL,
	conflict_retention				int					NULL,
	conflict_policy					int					NULL,
	queue_type						int					NULL,
	ad_guidname						nvarchar(128)		NULL,
	backward_comp_level				int				NOT	NULL,
	allow_initialize_from_backup	bit				NOT	NULL,
	min_autonosync_lsn				binary(10)			NULL,
	replicate_ddl					int					NULL,
	options							int				NOT	NULL,
	originator_id					int					NULL,

	INDEX CIX__syspublications__DatabaseID_pubid CLUSTERED (_DatabaseID, pubid),
);
GO
